MAX_TURNS  = 10
SCORE_THRESHOLD =  5.0
MAX_CONTIGUOUS_NON_TECHNICAL_GUARDRAIL_COUNT = 4
MAX_GUARDRAIL_COUNT = 10
MAX_CONTIGUOUS_TECHNICAL_GUARDRAIL_COUNT = 4
COMPLEXITY = 1
TOTAL_NUMBER_OF_QUESTIONS = 2